GET http://localhost:3000/transacoes/resumo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJicnVub2dtaW5pdHRpQGdtYWlsLmNvbSIsImlhdCI6MTc4NDMwNTQzOCwiZXhwIjoxNzg0OTEwMjM4fQ.Xc8hPz3n5oxYtWzScZlrsoHg42wXaihk5wBg-cdX7b0